# Generated by Django 4.1.3 on 2022-11-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
