# Generated by Django 4.1.3 on 2022-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
