# Generated by Django 4.1.3 on 2022-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
